name: flaa103 # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: flaa103 brings partial autoscaling to flaarum # 79 char long summary
description: |
  flaa103 brings partial autoscaling to flaarum

  flaarum is a database. More information on flaarum can be found at
  https://sae.ng/flaarumtuts/intro

  Partial Autoscaling

  flaa103 resizes a flaarum instance on Google Cloud platform every morning
  and evening.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf


parts:
  all-needed-files:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-snaps:
    - go


apps:
  flaa103:
    command: bin/flaa103
    plugs:
      - network

  gcasr:
    command: bin/gcpasr
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network
      - network-bind

  gcasrn:
    command: bin/gcasrn
    plugs:
      - network
